# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)


title: David Song's blog
subtitle: song_blog
email: david61song@protonmail.com

plugins:
  - jekyll-seo-tag
header_pages:
  - index.md
  - PGP.md
  - about.md
  - category.html

style: dark # dark (default), light or hacker
footer: 'Published by david song'

markdown: kramdown

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: true
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true
